#define GATEWAY_ADDRESS "<GATEWAY_ADDRESS>"
#define GATEWAY_SSL_FINGERPRINT "<GATEWAY_SSL_FINGERPRINT>"

#define NETWORK_SSID "<NETWORK_SSID>"
#define NETWORK_PASSWORD "<NETWORK_PASSWORD>"

#define ALLOWED_USERS "&users=<USER>"
